apiVersion: assistant.watson.ibm.com/v1
kind: TemporaryPatch
metadata:
  name: wo-wa-ed-grpc-dns-resolver
  namespace: cpd
spec:
  apiVersion: assistant.watson.ibm.com/v1
  kind: WatsonAssistantCluRuntime
  name: wo-wa
  patchType: patchStrategicMerge
  patch:
    ed:
      deployment:
        spec:
          template:
            spec:
              containers:
              - name: ed-mm
                env:
                - name: GRPC_DNS_RESOLVER
                  value: "native"
              - name: mm-runtime
                env:
                - name: GRPC_DNS_RESOLVER
                  value: "native"
